# Generated by Django 4.2 on 2024-03-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
