# Generated by Django 4.2 on 2024-03-06 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_items_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='total_quantity',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total quantity of Item'),
        ),
    ]
