# Generated by Django 4.2 on 2024-03-06 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_items_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Item Price'),
        ),
    ]
