# Generated by Django 4.2 on 2024-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='total_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total quantity of Item'),
        ),
    ]
