# Generated by Django 4.2 on 2024-03-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_total_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
