# Generated by Django 4.2 on 2024-03-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_items_options_alter_items_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['price', 'name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
