# Generated by Django 4.2 on 2024-03-21 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_total_quantity_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(editable=False, help_text="It will take todays date on it's itself"),
        ),
        migrations.AlterField(
            model_name='items',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Item's availability", verbose_name='Status of Item'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(help_text="Enter your item's name", max_length=70, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveSmallIntegerField(help_text="Enter your item's price (help in sorting the item sequentially)", validators=[django.core.validators.MinValueValidator(5)], verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text="Item's current quantity", verbose_name='Total quantity of Item'),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(editable=False, help_text="It will take todays date on it's itself"),
        ),
    ]
