# Generated by Django 4.2 on 2024-03-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_items_created_at_alter_items_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Click to change item's availability", verbose_name='Item Availability'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', help_text="Enter your item's name", max_length=50, validators=[django.core.validators.MinValueValidator(4)], verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveSmallIntegerField(help_text="Enter your item's price", validators=[django.core.validators.MinValueValidator(5)], verbose_name='Item Price'),
        ),
    ]
