# Generated by Django 4.2 on 2024-03-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_items_is_active_alter_items_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(editable=False, help_text="It will take todays date on it's itself", verbose_name='Created Time Of Item'),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(editable=False, help_text="It will take todays date on it's itself", verbose_name='Last Change In Quantity'),
        ),
    ]
