# Generated by Django 4.2 on 2024-03-24 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_items_created_at_alter_items_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', help_text="Enter your item's name", max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.SmallIntegerField(default=0, help_text="Item's current quantity", verbose_name='Total quantity of Item'),
        ),
    ]
