# Generated by Django 4.2 on 2024-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_alter_reports_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='reports',
            name='entry_date',
            field=models.DateField(auto_now_add=True, help_text="It will take todays date on it's own"),
        ),
    ]
