# Generated by Django 4.2 on 2024-03-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_items_created_at_alter_items_is_active_and_more'),
        ('report_app', '0003_alter_reports_options_alter_reports_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='arrival_stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='balance_stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='items',
            field=models.ForeignKey(default=None, help_text='Please choose a item to generate report', on_delete=django.db.models.deletion.PROTECT, to='items.items', verbose_name='Item Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='old_balance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='sold_stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='total_stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reports',
            unique_together={('items', 'entry_date')},
        ),
    ]
