# Generated by Django 4.2 on 2024-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_reports_arrival_stock_reports_balance_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='arrival_stock',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='balance_stock',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='old_balance',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='sold_stock',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='total_stock',
            field=models.SmallIntegerField(),
        ),
    ]
