# Generated by Django 4.2 on 2024-03-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_reports_arrival_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='old_balance',
            new_name='old_stock',
        ),
    ]
