# Generated by Django 4.2 on 2024-03-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0009_alter_items_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_quantity', models.SmallIntegerField(help_text='Please enter a quantity greater than or equal to 1', verbose_name='Supply Quantity')),
                ('supply_date', models.DateField(auto_now_add=True)),
                ('items', models.ForeignKey(help_text='Please choose a item to supply', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='items.items', verbose_name='Item Supplied')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplys',
                'ordering': ['-supply_date'],
                'unique_together': {('items', 'supply_date')},
            },
        ),
    ]
