# Generated by Django 4.2 on 2024-03-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_items_options'),
        ('supply_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplys',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Supply', 'verbose_name_plural': 'Supplys'},
        ),
        migrations.RenameField(
            model_name='supplys',
            old_name='supply_date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='supplys',
            old_name='supply_quantity',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='supplys',
            unique_together={('items', 'entry_date')},
        ),
    ]
