# Generated by Django 4.2 on 2024-03-06 03:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0007_alter_items_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Import Quantity')),
                ('import_date', models.DateField(auto_now_add=True)),
                ('import_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.items', verbose_name='Item to be imported')),
            ],
            options={
                'unique_together': {('items', 'import_date')},
            },
        ),
    ]
