# Generated by Django 4.2 on 2024-03-13 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_items_options'),
        ('import_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imports',
            options={'ordering': ['-import_date'], 'verbose_name': 'Import', 'verbose_name_plural': 'Imports'},
        ),
        migrations.RemoveField(
            model_name='imports',
            name='import_by',
        ),
        migrations.AlterField(
            model_name='imports',
            name='import_quantity',
            field=models.PositiveSmallIntegerField(help_text='Please enter a quantity greater than or equal to 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Import Quantity'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='items',
            field=models.ForeignKey(help_text='Please choose a item to import', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='items.items', verbose_name='Item Imported'),
        ),
    ]
