# Generated by Django 4.2 on 2024-03-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_items_options'),
        ('import_app', '0002_alter_imports_options_remove_imports_import_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imports',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Import', 'verbose_name_plural': 'Imports'},
        ),
        migrations.RenameField(
            model_name='imports',
            old_name='import_date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='imports',
            old_name='import_quantity',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='imports',
            unique_together={('items', 'entry_date')},
        ),
    ]
