# Generated by Django 4.2 on 2024-03-21 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0003_alter_imports_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imports',
            name='entry_date',
            field=models.DateField(auto_now_add=True, help_text="It will take todays date on it's own"),
        ),
        migrations.AlterField(
            model_name='imports',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Please enter your imported quantity here', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Import Quantity'),
        ),
    ]
