# Generated by Django 4.2 on 2024-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0004_alter_imports_entry_date_alter_imports_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imports',
            name='quantity',
            field=models.SmallIntegerField(help_text='Please enter your imported quantity here', verbose_name='Import Quantity'),
        ),
    ]
